// ...existing code...
const bcrypt = require("bcryptjs");
// ...existing code...
bcrypt.hash(password, saltRounds, function(err, hash) {
  // ...existing code...
});
// ...existing code...
bcrypt.compare(password, hash, function(err, res) {
  // ...existing code...
});
// ...existing code...